name: C++ tutorial
channels:
  - conda-forge
dependencies:
  - xeus-cling=0.12.0
  - xtensor=0.23.0
  - xtensor-blas=0.19.0
  - gcc=9.4.0
  - notebook
  - python
  - numpy
  - pip
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
